name: Automated Tests

on:
  pull_request:
    branches:
      - master
  push:
  workflow_dispatch:

jobs:
  gitHubActionForPytest:
    name: GitHub Action for pytest
    strategy:
      matrix:
        python-version: [3.11]
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository
        uses: actions/checkout@v4

      - name: Enable version ${{ matrix.python-version }} of Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          make test
